sex-specific

diff --git a/cdts_calc b/cdts_calc
--- a/cdts_calc
+++ b/cdts_calc
@@ -1,130 +1,132 @@
 #!/bin/bash
 set -e
 
-extract_tolerance_score() {
+extract_tolerance_score_specific() {
     start=$(date +%s)
     log "Computing Tolerance Score"
-
-    awk -v OFS='\t' -F'\t' '{print $1, 0}' $1/"$2"mermetrics/"$2"mer_highconf_gnomadupdate_hg38_autosomesAndPAR.txt \
-        > $1/"$2"mermetrics/"$2"mer_variation_afabovethreshold_highconf_gnomadupdate_hg38_autosomesAndPAR.txt
+    CHOICE=$6
+    awk -v OFS='\t' -F'\t' '{print $1, 0}' $1/"$2"mermetrics/$CHOICE/"$2"mer_highconf_gnomadupdate_hg38_autosomesAndPAR.txt \
+        > $1/"$2"mermetrics/$CHOICE/"$2"mer_variation_afabovethreshold_highconf_gnomadupdate_hg38_autosomesAndPAR.txt
     
     afth=$3
     for chroms in $(seq 1 22 | cat - <(echo "XPAR"))
     do
         
         # first extract kmeric sequence from positions that vary with af above the specified threshold (but not coming from singletons)
-        [ ! -s $1/af/gnomad_PASS_SNV_chr${chroms}_afabovethreshold_highconf.bed.gz ] &&
-            unstarch $1/af/gnomad_PASS_SNV_chr${chroms}_af_highconf.starch \
+        [ ! -s $1/af/$CHOICE/gnomad_PASS_SNV_chr${chroms}_afabovethreshold_highconf.bed.gz ] &&
+            unstarch $1/af/$CHOICE/gnomad_PASS_SNV_chr${chroms}_af_highconf.starch \
             | grep -v "sglt" \
             | awk -v OFS='\t' -F'\t' -v af=${afth} '{if ($11>=af) print $0}' \
-            | bedmap --echo --echo-map-id --skip-unmapped - <(zcat $1/genome/"$2"mer_hg38_highconf_gnomadupdate_chr${chroms}.bed.gz \
+            | bedmap --echo --echo-map-id --skip-unmapped - <(zcat $1/genome/$CHOICE/"$2"mer_hg38_highconf_gnomadupdate_chr${chroms}.bed.gz \
                 | sed 's/::/\t/g' \
                 | cut -f1,2,3,5) \
             | sed 's/|/\t/g' \
             | gzip - \
-            > $1/af/gnomad_PASS_SNV_chr${chroms}_afabovethreshold_highconf.bed.gz
+            > $1/af/$CHOICE/gnomad_PASS_SNV_chr${chroms}_afabovethreshold_highconf.bed.gz
         
         # extract counts of kmer that vary with an allelic frequency above the specified threshold
-        [ ! -s $1/"$2"mermetrics/"$2"mer_variation_afabovethreshold_highconf_gnomadupdate_hg38_chr${chroms}.txt ] &&
-            zcat $1/af/gnomad_PASS_SNV_chr${chroms}_afabovethreshold_highconf.bed.gz \
+        [ ! -s $1/"$2"mermetrics/$CHOICE/"$2"mer_variation_afabovethreshold_highconf_gnomadupdate_hg38_chr${chroms}.txt ] &&
+            zcat $1/af/$CHOICE/gnomad_PASS_SNV_chr${chroms}_afabovethreshold_highconf.bed.gz \
             | cut -f 14 \
             | python $5/countkmer.py 1 $2 \
-            > $1/"$2"mermetrics/"$2"mer_variation_afabovethreshold_highconf_gnomadupdate_hg38_chr${chroms}.txt
+            > $1/"$2"mermetrics/$CHOICE/"$2"mer_variation_afabovethreshold_highconf_gnomadupdate_hg38_chr${chroms}.txt
         
         # sum all kmer counts from autosomes and PAR
-        paste $1/"$2"mermetrics/"$2"mer_variation_afabovethreshold_highconf_gnomadupdate_hg38_autosomesAndPAR.txt \
-            $1/"$2"mermetrics/"$2"mer_variation_afabovethreshold_highconf_gnomadupdate_hg38_chr${chroms}.txt \
+        paste $1/"$2"mermetrics/$CHOICE/"$2"mer_variation_afabovethreshold_highconf_gnomadupdate_hg38_autosomesAndPAR.txt \
+            $1/"$2"mermetrics/$CHOICE/"$2"mer_variation_afabovethreshold_highconf_gnomadupdate_hg38_chr${chroms}.txt \
             | awk -v OFS='\t' -F'\t' '{if ($1==$3) print $1, $2+$4}' \
             > tmp.txt
-        mv tmp.txt $1/"$2"mermetrics/"$2"mer_variation_afabovethreshold_highconf_gnomadupdate_hg38_autosomesAndPAR.txt
+        mv tmp.txt $1/"$2"mermetrics/$CHOICE/"$2"mer_variation_afabovethreshold_highconf_gnomadupdate_hg38_autosomesAndPAR.txt
         log "Computed for chrom $chroms"
     done
    
     # do the same thing for the X chromosome
     afth=$4
-    [ ! -s $1/af/gnomad_PASS_SNV_chrXnotPAR_afabovethreshold_highconf.bed.gz ] &&
-        unstarch $1/af/gnomad_PASS_SNV_chrXnotPAR_af_highconf.starch \
+    [ ! -s $1/af/$CHOICE/gnomad_PASS_SNV_chrXnotPAR_afabovethreshold_highconf.bed.gz ] &&
+        unstarch $1/af/$CHOICE/gnomad_PASS_SNV_chrXnotPAR_af_highconf.starch \
         | grep -v "sglt" \
         | awk -v OFS='\t' -F'\t' -v af=${afth} '{if ($11>=af) print $0}' \
-        | bedmap --echo --echo-map-id --skip-unmapped - <(zcat $1/genome/"$2"mer_hg38_highconf_gnomadupdate_chrXnotPAR.bed.gz \
+        | bedmap --echo --echo-map-id --skip-unmapped - <(zcat $1/genome/$CHOICE/"$2"mer_hg38_highconf_gnomadupdate_chrXnotPAR.bed.gz \
         | sed 's/::/\t/g' \
         | cut -f1,2,3,5) \
         | sed 's/|/\t/g' \
         | gzip - \
-        > $1/af/gnomad_PASS_SNV_chrXnotPAR_afabovethreshold_highconf.bed.gz
+        > $1/af/$CHOICE/gnomad_PASS_SNV_chrXnotPAR_afabovethreshold_highconf.bed.gz
     
-    [ ! -s $1/"$2"mermetrics/"$2"mer_variation_afabovethreshold_highconf_gnomadupdate_hg38_chrXnotPAR.txt ] &&
-        zcat $1/af/gnomad_PASS_SNV_chrXnotPAR_afabovethreshold_highconf.bed.gz \
+    [ ! -s $1/"$2"mermetrics/$CHOICE/"$2"mer_variation_afabovethreshold_highconf_gnomadupdate_hg38_chrXnotPAR.txt ] &&
+        zcat $1/af/$CHOICE/gnomad_PASS_SNV_chrXnotPAR_afabovethreshold_highconf.bed.gz \
         | cut -f 14 \
         | python $5/countkmer.py 1 $2 \
-        > $1/"$2"mermetrics/"$2"mer_variation_afabovethreshold_highconf_gnomadupdate_hg38_chrXnotPAR.txt
+        > $1/"$2"mermetrics/$CHOICE/"$2"mer_variation_afabovethreshold_highconf_gnomadupdate_hg38_chrXnotPAR.txt
   
     # make tolerance fraction. divide the obs count by the observed
-    mkdir -p $1/"$2"mermetrics/Dico
-    paste $1/"$2"mermetrics/"$2"mer_highconf_gnomadupdate_hg38_autosomesAndPAR.txt \
-        $1/"$2"mermetrics/"$2"mer_variation_afabovethreshold_highconf_gnomadupdate_hg38_autosomesAndPAR.txt \
+    mkdir -p $1/"$2"mermetrics/$CHOICE/Dico
+    paste $1/"$2"mermetrics/$CHOICE/"$2"mer_highconf_gnomadupdate_hg38_autosomesAndPAR.txt \
+        $1/"$2"mermetrics/$CHOICE/"$2"mer_variation_afabovethreshold_highconf_gnomadupdate_hg38_autosomesAndPAR.txt \
     | awk -v OFS='\t' -F'\t' '{if ($1==$3) print $1, $4/$2}' \
-    > $1/"$2"mermetrics/Dico/TS_autosomesAndPAR.txt
+    > $1/"$2"mermetrics/$CHOICE/Dico/TS_autosomesAndPAR.txt
     
-    paste $1/"$2"mermetrics/"$2"mer_highconf_gnomadupdate_hg38_chrXnotPAR.txt \
-        $1/"$2"mermetrics/"$2"mer_variation_afabovethreshold_highconf_gnomadupdate_hg38_chrXnotPAR.txt \
+    paste $1/"$2"mermetrics/$CHOICE/"$2"mer_highconf_gnomadupdate_hg38_chrXnotPAR.txt \
+        $1/"$2"mermetrics/$CHOICE/"$2"mer_variation_afabovethreshold_highconf_gnomadupdate_hg38_chrXnotPAR.txt \
     | awk -v OFS='\t' -F'\t' '{if ($1==$3 && $2!=0) {print $1, $4/$2} else {print $1, -1}}' \
-    > $1/"$2"mermetrics/Dico/TS_chrXnotPAR.txt
+    > $1/"$2"mermetrics/$CHOICE/Dico/TS_chrXnotPAR.txt
     
     end=$(date +%s)
     runtime=$(((end-start)/60))
     log "Time Taken" "$runtime minutes"
 }
 
-place_tol_score() {
+place_tol_score_specific() {
     start=$(date +%s)
     log "Placing tolerance score in genomic location"
+    CHOICE=$4
     for chroms in $(seq 1 22 | cat - <(echo "XPAR"))
     do
         log "Placing chrom $chroms"
-        if [ ! -s $1/genome/"$2"mer_TS_hg38_highconf_gnomadupdate_chr${chroms}.bed.gz ]; then
-            zcat $1/genome/"$2"mer_hg38_highconf_gnomadupdate_chr${chroms}.bed.gz \
-                | python $3/placeKmerToleranceScoreFromDicotoGenomicCoordinate_onlyACGT.py $1/"$2"mermetrics/Dico/TS_autosomesAndPAR.txt $2 \
+        if [ ! -s $1/genome/$CHOICE/"$2"mer_TS_hg38_highconf_gnomadupdate_chr${chroms}.bed.gz ]; then
+            zcat $1/genome/$CHOICE/"$2"mer_hg38_highconf_gnomadupdate_chr${chroms}.bed.gz \
+                | python $3/placeKmerToleranceScoreFromDicotoGenomicCoordinate_onlyACGT.py $1/"$2"mermetrics/$CHOICE/Dico/TS_autosomesAndPAR.txt $2 \
                 | gzip - \
-                > $1/genome/"$2"mer_TS_hg38_highconf_gnomadupdate_chr${chroms}.bed.gz &
+                > $1/genome/$CHOICE/"$2"mer_TS_hg38_highconf_gnomadupdate_chr${chroms}.bed.gz &
         else
             continue
         fi
     done
     wait
     
-    [ ! -f $1/genome/"$2"mer_TS_hg38_highconf_gnomadupdate_chrXnotPAR.bed.gz ] &&
-        zcat $1/genome/"$2"mer_hg38_highconf_gnomadupdate_chrXnotPAR.bed.gz \
-            | python $3/placeKmerToleranceScoreFromDicotoGenomicCoordinate_onlyACGT.py $1/"$2"mermetrics/Dico/TS_chrXnotPAR.txt $2 \
+    [ ! -f $1/genome/$CHOICE/"$2"mer_TS_hg38_highconf_gnomadupdate_chrXnotPAR.bed.gz ] &&
+        zcat $1/genome/$CHOICE/"$2"mer_hg38_highconf_gnomadupdate_chrXnotPAR.bed.gz \
+            | python $3/placeKmerToleranceScoreFromDicotoGenomicCoordinate_onlyACGT.py $1/"$2"mermetrics/$CHOICE/Dico/TS_chrXnotPAR.txt $2 \
             | gzip - \
-            > $1/genome/"$2"mer_TS_hg38_highconf_gnomadupdate_chrXnotPAR.bed.gz
+            > $1/genome/$CHOICE/"$2"mer_TS_hg38_highconf_gnomadupdate_chrXnotPAR.bed.gz
 
     end=$(date +%s)
     runtime=$(((end-start)/60))
     log "Time Taken" "$runtime minutes"
 }
 
-generate_obsexpected() {
+generate_obsexpected_specific() {
     start=$(date +%s)
     log "Generating window"
-    mkdir -p $1/CDTS
+    mkdir -p $1/CDTS/$CHOICE
     window=$3
     sliding=$4
     leftright_gap=$((($window/2) - 5))
+    CHOICE=$5
     while read -r chroms; do
         bluntchr=`echo $chroms | sed -e 's/PAR//g' -e 's/not//g'`
         log "Computing expected for chrom $chroms"
-        if [ ! -s $1/CDTS/CDTS_diff_chr${chroms}.bed.gz ]; then
+        if [ ! -s $1/CDTS/$CHOICE/CDTS_diff_chr${chroms}.bed.gz ]; then
         grep -w ${bluntchr} $1/genome/chrLength_hg38.txt \
             | awk -v OFS='\t' -F'\t' -v sld=$sliding -v wd=$window '{for(i=0; i<=($2); i=i+sld) {stt=i;end=i+wd; print $1, stt,end}}' \
-            | bedmap --echo --bases --sum - <(zcat $1/genome/"$2"mer_TS_hg38_highconf_gnomadupdate_chr${chroms}.bed.gz) \
+            | bedmap --echo --bases --sum - <(zcat $1/genome/$CHOICE/"$2"mer_TS_hg38_highconf_gnomadupdate_chr${chroms}.bed.gz) \
             | sed 's/|/\t/g' \
             | awk -v OFS='\t' -F'\t' -v wd=$window '{if ($4 >= wd*0.9) print $0}' \
-            | bedmap --echo --count - <(zcat $1/af/gnomad_PASS_SNV_chr${chroms}_afabovethreshold_highconf.bed.gz) \
+            | bedmap --echo --count - <(zcat $1/af/$CHOICE/gnomad_PASS_SNV_chr${chroms}_afabovethreshold_highconf.bed.gz) \
             | sed 's/|/\t/g' \
             | awk -v OFS='\t' -F'\t' -v g="$leftright_gap" '{print $1, $2+g, $3-g, $6, $5, $6-$5}' \
             | gzip - \
-            > $1/CDTS/CDTS_diff_chr${chroms}.bed.gz &
+            > $1/CDTS/$CHOICE/CDTS_diff_chr${chroms}.bed.gz &
         else
             continue
         fi
@@ -135,14 +137,15 @@ generate_obsexpected() {
     log "Time Taken" "$runtime minutes"
 }
 
-create_percentile_bins() {
+create_percentile_bins_specific() {
     start=$(date +%s)
     log "Creating percentile bins"
-    nb=$(($(zcat $1/CDTS/CDTS_diff_chr*.bed.gz | wc -l)/100))
-    mkdir -p $1/CDTS/split/diff
-    zcat $1/CDTS/CDTS_diff_chr*.bed.gz > $1/CDTS/split/genome_CDTS.bed
-    sort -k6,6g -k4,4n --temporary-directory=$1/CDTS/split/diff $1/CDTS/split/genome_CDTS.bed \
-        | split -l $nb --numeric-suffixes=1 --suffix-length=3 - $1/CDTS/split/diff/CDTS_diff_perc.bed.
+    CHOICE=$2
+    nb=$(($(zcat $1/CDTS/$CHOICE/CDTS_diff_chr*.bed.gz | wc -l)/100))
+    mkdir -p $1/CDTS/$CHOICE/split/diff
+    zcat $1/CDTS/$CHOICE/CDTS_diff_chr*.bed.gz > $1/CDTS/$CHOICE/split/genome_CDTS.bed
+    sort -k6,6g -k4,4n --temporary-directory=$1/CDTS/$CHOICE/split/diff $1/CDTS/$CHOICE/split/genome_CDTS.bed \
+        | split -l $nb --numeric-suffixes=1 --suffix-length=3 - $1/CDTS/$CHOICE/split/diff/CDTS_diff_perc.bed.
     end=$(date +%s)
     runtime=$(((end-start)/60))
     log "Time Taken" "$runtime minutes"
@@ -190,6 +193,7 @@ main() {
     AFTHX=0.000075
     SLIDING=10
     WINDOW=550
+    OPTIONS="male female"
     for i in "$@"; do
     case $i in
         -o|--outdir)
@@ -227,6 +231,11 @@ main() {
         shift
         shift
         ;;
+        -ch|--choice)
+        OPTIONS="$2"
+        shift
+        shift
+        ;;
         -h|--help)
         usage
         exit
@@ -239,16 +248,24 @@ main() {
     log "Extracting CDTS score" "..." "STEP 4"
     
     log "Computing tolerance score" "..." "STEP 4A"
-    extract_tolerance_score $OUTDIR $KMER $AFTH $AFTHX $WD && log "SUCCESSFUL" "Tolerance score calculated" "STEP 4A" || die "Step 4A failed"
+    for CHOICE in $OPTIONS; do 
+        extract_tolerance_score_specific $OUTDIR $KMER $AFTH $AFTHX $WD $CHOICE && log "SUCCESSFUL" "Tolerance score calculated" "STEP 4A" || die "Step 4A failed"
+    done
     
     log "Placing tolerance score" "..." "STEP 4B"
-    place_tol_score $OUTDIR $KMER $WD && log "SUCCESSFUL" "Tolerance score placed" "STEP 4B" || die "Step 4B failed"
+    for CHOICE in $OPTIONS; do 
+        place_tol_score_specific $OUTDIR $KMER $WD $CHOICE && log "SUCCESSFUL" "Tolerance score placed" "STEP 4B" || die "Step 4B failed"
+    done
     
     log "Computing observed and expected values" "..." "STEP 4C"
-    generate_obsexpected $OUTDIR $KMER $WINDOW $SLIDING && log "SUCCESSFUL" "Observed and Expected computed" "STEP 4C" || die "Step 4C failed"
+    for CHOICE in $OPTIONS; do 
+        generate_obsexpected_specific $OUTDIR $KMER $WINDOW $SLIDING $CHOICE && log "SUCCESSFUL" "Observed and Expected computed" "STEP 4C" || die "Step 4C failed"
+    done
     
     log "Create percentile bins" "..." "STEP 4D"
-    create_percentile_bins $OUTDIR && log "SUCCESSFUL" "Percentile bins created" "STEP 4D" || die "Step 4D failed"
+    for CHOICE in $OPTIONS; do 
+        create_percentile_bins_specific $OUTDIR $CHOICE && log "SUCCESSFUL" "Percentile bins created" "STEP 4D" || die "Step 4D failed"
+    done
     exit
     
     log "Merge all bins" "..." "STEP 4E"
diff --git a/kmer_calc b/kmer_calc
--- a/kmer_calc
+++ b/kmer_calc
@@ -1,10 +1,11 @@
 #!/bin/bash
 set -e
 
-get_kmer() {
+get_kmer_specific() {
     start=$(date +%s)
     log "Downloading hg38 reference"
     mkdir -p $1/genome
+    CHOICE=$3
     wget -q -N -P $1/genome "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.chrom.sizes"
     cat $1/genome/hg38.chrom.sizes | head -24 | sed 's/^chr//g' > $1/genome/chrLength_hg38.txt
     if [ ! -f $1/genome/hg38_reference.fasta ]; then
@@ -39,21 +40,22 @@ get_kmer() {
     runtime=$(((end-start)/60))
     log "Time Taken" "$runtime minutes"
 
+    mkdir -p $1/genome/$CHOICE
     log "Remove everything that didn't pass QC and update reference nucleotide where it differs from hg38"
     for chroms in $(seq 1 22); do
         log "Filtering chrom $chroms"
-        if [ ! -f $1/genome/"$2"mer_hg38_highconf_gnomadupdate_chr"$chroms".bed.gz ]; then
+        if [ ! -f $1/genome/$CHOICE/"$2"mer_hg38_highconf_gnomadupdate_chr"$chroms".bed.gz ]; then
             bedmap --echo --skip-unmapped <(zcat $1/genome/"$2"mer_hg38_chr${chroms}_noN.bed.gz) \
-                $1/qc/confidentRegions_nolowcov_nohighmissingness_hg38_autosomesAndPAR.starch \
+                $1/qc/$CHOICE/confidentRegions_nolowcov_nohighmissingness_hg38_autosomesAndPAR.starch \
             | bedmap --echo --echo-map-id --echo-map-score - \
-                $1/af/gnomad_PASS_SNV_chr${chroms}_af_highconf_wrongref_idx_newref.starch \
+                $1/af/$CHOICE/gnomad_PASS_SNV_chr${chroms}_af_highconf_wrongref_idx_newref.starch \
             | sed -e 's/||$//' -e 's/|/\t/g' \
             | awk -v OFS='\t' -F'\t' '{if (NF==4) print $0; \
                 else {split($4,seq,""); split($5,ref,";"); split($6,idx,";"); \
                 for (i=1;i<=length(idx);i++) seq[int(idx[i])]=ref[i]; \
                 print $1, $2, $3, seq[1]seq[2]seq[3]seq[4]seq[5]seq[6]seq[7]}}' \
             | gzip - \
-            > $1/genome/"$2"mer_hg38_highconf_gnomadupdate_chr"$chroms".bed.gz &
+            > $1/genome/$CHOICE/"$2"mer_hg38_highconf_gnomadupdate_chr"$chroms".bed.gz &
         else
             continue
         fi
@@ -61,60 +63,61 @@ get_kmer() {
     wait
 
     log "Filtering XPAR"
-    if [ ! -f $1/genome/"$2"mer_hg38_highconf_gnomadupdate_chrXPAR.bed.gz ]; then 
-        bedmap --echo --skip-unmapped <(zcat $1/genome/"$2"mer_hg38_chrX_noN.bed.gz) $1/qc/confidentRegions_nolowcov_nohighmissingness_hg38_autosomesAndPAR.starch \
+    if [ ! -f $1/genome/$CHOICE/"$2"mer_hg38_highconf_gnomadupdate_chrXPAR.bed.gz ]; then 
+        bedmap --echo --skip-unmapped <(zcat $1/genome/"$2"mer_hg38_chrX_noN.bed.gz) $1/qc/$CHOICE/confidentRegions_nolowcov_nohighmissingness_hg38_autosomesAndPAR.starch \
         | bedmap --echo --echo-map-id --echo-map-score - \
-            $1/af/gnomad_PASS_SNV_chrXPAR_af_highconf_wrongref_idx_newref.starch \
+            $1/af/$CHOICE/gnomad_PASS_SNV_chrXPAR_af_highconf_wrongref_idx_newref.starch \
         | sed -e 's/||$//' -e 's/|/\t/g' \
         | awk -v OFS='\t' -F'\t' '{if (NF==4) print $0; \
             else {split($4,seq,""); split($5,ref,";"); split($6,idx,";"); \
             for (i=1;i<=length(idx);i++) seq[int(idx[i])]=ref[i]; \
             print $1, $2, $3, seq[1]seq[2]seq[3]seq[4]seq[5]seq[6]seq[7]}}' \
         | gzip - \
-        > $1/genome/"$2"mer_hg38_highconf_gnomadupdate_chrXPAR.bed.gz
+        > $1/genome/$CHOICE/"$2"mer_hg38_highconf_gnomadupdate_chrXPAR.bed.gz
     fi
     
     log "Filtering notXPAR"
     if [ ! -f $1/genome/"$2"mer_hg38_highconf_gnomadupdate_chrXnotPAR.bed.gz ]; then 
-        bedmap --echo --skip-unmapped <(zcat $1/genome/"$2"mer_hg38_chrX_noN.bed.gz) $1/qc/confidentRegions_nolowcov_nohighmissingness_hg38_chrXnotPAR.starch \
-        | bedmap --echo --echo-map-id --echo-map-score - $1/af/gnomad_PASS_SNV_chrXnotPAR_af_highconf_wrongref_idx_newref.starch \
+        bedmap --echo --skip-unmapped <(zcat $1/genome/"$2"mer_hg38_chrX_noN.bed.gz) $1/qc/$CHOICE/confidentRegions_nolowcov_nohighmissingness_hg38_chrXnotPAR.starch \
+        | bedmap --echo --echo-map-id --echo-map-score - $1/af/$CHOICE/gnomad_PASS_SNV_chrXnotPAR_af_highconf_wrongref_idx_newref.starch \
         | sed -e 's/||$//' -e 's/|/\t/g' \
         | awk -v OFS='\t' -F'\t' '{if (NF==4) print $0; \
             else {split($4,seq,""); split($5,ref,";"); split($6,idx,";"); \
                 for (i=1;i<=length(idx);i++) seq[int(idx[i])]=ref[i]; \
                     print $1, $2, $3, seq[1]seq[2]seq[3]seq[4]seq[5]seq[6]seq[7]}}' \
         | gzip - \
-        > $1/genome/"$2"mer_hg38_highconf_gnomadupdate_chrXnotPAR.bed.gz
+        > $1/genome/$CHOICE/"$2"mer_hg38_highconf_gnomadupdate_chrXnotPAR.bed.gz
     fi
     end=$(date +%s)
     runtime=$(((end-start)/60))
     log "Time Taken" "$runtime minutes"
 }
 
-extract_kmer_counts() {
+extract_kmer_counts_specific() {
     start=$(date +%s)
-    mkdir -p "$1"/"$2"mermetrics
+    CHOICE=$4
+    mkdir -p "$1"/"$2"mermetrics/$CHOICE
     while read -r chroms; do
         log "Extracting kmer counts for chr$chroms"
-        if [ ! -s "$1"/"$2"mermetrics/"$2"mer_highconf_gnomadupdate_hg38_chr${chroms}.txt ]
+        if [ ! -s "$1"/"$2"mermetrics/$CHOICE/"$2"mer_highconf_gnomadupdate_hg38_chr${chroms}.txt ]
         then
-            zcat $1/genome/"$2"mer_hg38_highconf_gnomadupdate_chr${chroms}.bed.gz \
+            zcat $1/genome/$CHOICE/"$2"mer_hg38_highconf_gnomadupdate_chr${chroms}.bed.gz \
                 | cut -f 4 \
                 | python $3/countkmer.py 1 $2 \
-                > "$1"/"$2"mermetrics/"$2"mer_highconf_gnomadupdate_hg38_chr${chroms}.txt &
+                > "$1"/"$2"mermetrics/$CHOICE/"$2"mer_highconf_gnomadupdate_hg38_chr${chroms}.txt &
         else
             continue
         fi
     done < $1/chromList_PARsplit.txt
     wait
 
-    cp "$1"/"$2"mermetrics/"$2"mer_highconf_gnomadupdate_hg38_chrXPAR.txt \
-        "$1"/"$2"mermetrics/"$2"mer_highconf_gnomadupdate_hg38_autosomesAndPAR.txt
+    cp "$1"/"$2"mermetrics/$CHOICE/"$2"mer_highconf_gnomadupdate_hg38_chrXPAR.txt \
+        "$1"/"$2"mermetrics/$CHOICE/"$2"mer_highconf_gnomadupdate_hg38_autosomesAndPAR.txt
     for chroms in `seq 1 22`; do
-        paste "$1"/"$2"mermetrics/"$2"mer_highconf_gnomadupdate_hg38_autosomesAndPAR.txt \
-         "$1"/"$2"mermetrics/"$2"mer_highconf_gnomadupdate_hg38_chr${chroms}.txt | \
+        paste "$1"/"$2"mermetrics/$CHOICE/"$2"mer_highconf_gnomadupdate_hg38_autosomesAndPAR.txt \
+         "$1"/"$2"mermetrics/$CHOICE/"$2"mer_highconf_gnomadupdate_hg38_chr${chroms}.txt | \
             awk -v OFS='\t' -F'\t' '{if ($1==$3) print $1, $2+$4}' > $1/tmp.txt
-        mv $1/tmp.txt "$1"/"$2"mermetrics/"$2"mer_highconf_gnomadupdate_hg38_autosomesAndPAR.txt
+        mv $1/tmp.txt "$1"/"$2"mermetrics/$CHOICE/"$2"mer_highconf_gnomadupdate_hg38_autosomesAndPAR.txt
     done
     end=$(date +%s)
     runtime=$(((end-start)/60))
@@ -136,6 +139,7 @@ main() {
     OUTDIR=""
     KMER=7
     WD="."
+    OPTIONS="male female"
     for i in "$@"; do
     case $i in
         -o|--outdir)
@@ -153,6 +157,11 @@ main() {
         shift
         shift
         ;;
+        -ch|--choice)
+        OPTIONS="$2"
+        shift
+        shift
+        ;;
         -h|--help)
         usage
         exit
@@ -166,10 +175,15 @@ main() {
     [[ $(($KMER%2)) == 0 ]] && die "Kmer value selected is not odd!" 
     
     log "Computing kmers for each position" "..." "STEP 3A"
-    get_kmer $OUTDIR $KMER && log "SUCCESSFUL" "Kmer computed for each position" "STEP 3A" || die "Step 3A failed"
+    for CHOICE in $OPTIONS; do 
+        get_kmer_specific $OUTDIR $KMER $CHOICE && log "SUCCESSFUL" "Kmer computed for each position" "STEP 3A" || die "Step 3A failed"
+    done
+    
     
     log "Extract kmer metrics" "..." "STEP 3B"
-    extract_kmer_counts $OUTDIR $KMER $WD && log "SUCCESSFUL" "Kmer metrics computed" "STEP 3B" || die "Step 3B failed"
+    for CHOICE in $OPTIONS; do 
+        extract_kmer_counts_specific $OUTDIR $KMER $WD $CHOICE && log "SUCCESSFUL" "Kmer metrics computed" "STEP 3B" || die "Step 3B failed"
+    done
 }
 
 main "$@"
diff --git a/qc b/qc
--- a/qc
+++ b/qc
@@ -80,6 +80,7 @@ find_passing_snvs() {
     while read -r chroms; do
         log "Filtering chrom $chroms"
         if [ ! -s $1/af/gnomad_PASS_SNV_chr${chroms}_af.starch ]; then
+            # changing this to something more agnostic is prefereable
             tabix $2/vcf/gnomad.genomes.r3.0.sites.chr${chroms}.vcf.bgz chr${chroms} \
                 | sed 's/^chr//g' \
                 | awk -v OFS='\t' -F'\t' '{if ($7=="PASS" && length($4)==1 && \
@@ -100,17 +101,50 @@ find_passing_snvs() {
     log "Time Taken" "$runtime minutes"
 }
 
-find_high_missingness() {
+find_passing_snvs_specific() {
     start=$(date +%s)
+    CHOICE=$4
+    mkdir -p $1/af/$CHOICE
+    while read -r chroms; do
+        if [ ! -s $1/af/$CHOICE/gnomad_PASS_SNV_chr${chroms}_af.starch ]; then
+            log "Filtering chrom $chroms for $CHOICE"
+            # changing this to something more agnostic is prefereable
+            tabix $2/vcf/gnomad.genomes.r3.0.sites.chr${chroms}.vcf.bgz chr${chroms} \
+                | sed 's/^chr//g' \
+                | awk -v OFS='\t' -F'\t' '{if ($7=="PASS" && length($4)==1 && \
+                (length($5)==1 || (length($5)==3 && $5~",") || (length($5)==5 && $5~",.,"))) print $1, $2-1, $2, $4, $5, $8}' \
+                | sed -e "s/;AC_$CHOICE=/\t/" -e "s/;AF_$CHOICE=/\t/" -e "s/;AN_$CHOICE=/\t/" \
+                | awk -v OFS='\t' '{print $1, $2, $3, $4, $5, $7, $8, $9}' \
+                | sed -e 's/;.*//' \
+                | awk '{if ($6!=0){print $0}}' \
+                | awk -v OFS='\t' -F'\t' '{split($5,alt,","); split($6,ac,","); split($8,af,","); \
+                    for (i=1;i<=length(alt);i++) print $1, $2, $3, $4, alt[i], ac[i], af[i], $7}' \
+                | awk -F'\t' -v OFS='\t' '{if(NF==8){print $0}}' \
+                | python $3/reformat_ACAFAN_1linePerPos_addFlags.py \
+                | starch - \
+                > $1/af/$CHOICE/gnomad_PASS_SNV_chr${chroms}_af.starch &
+        else
+            log "  Already filtered... skipping."
+        fi
+    done < $1/chromList.txt
+    wait
+    end=$(date +%s)
+    runtime=$(((end-start)/60))
+    log "Time Taken" "$runtime minutes"
+}
+
+find_high_missingness_specific() {
+    start=$(date +%s)
+    CHOICE=$2
     nball=1000
     while read -r chroms; do
         log "Filtering chrom $chroms"
-        if [ ! -s $1/af/gnomad_PASS_SNV_chr${chroms}_high_missingness.starch ]; then
-            unstarch $1/af/gnomad_PASS_SNV_chr${chroms}_af.starch \
+        if [ ! -s $1/af/$CHOICE/gnomad_PASS_SNV_chr${chroms}_high_missingness.starch ]; then
+            unstarch $1/af/$CHOICE/gnomad_PASS_SNV_chr${chroms}_af.starch \
                 | awk -v OFS='\t' -F'\t' -v nb=$nball '{if($13 < nb) {print $1,$2,$3}}' \
                 | bedops -m - \
                 | starch - \
-                > $1/af/gnomad_PASS_SNV_chr${chroms}_high_missingness.starch &
+                > $1/af/$CHOICE/gnomad_PASS_SNV_chr${chroms}_high_missingness.starch &
         else
             log "  Already filtered... skipping."
         fi
@@ -118,30 +152,31 @@ find_high_missingness() {
     wait
 
     log "Splitting into pseudoautosomal regions and nonPAR"
-    [ ! -s $1/af/gnomad_PASS_SNV_chrXPAR_high_missingness.starch ] &&
-        bedops --intersect $1/af/gnomad_PASS_SNV_chrX_high_missingness.starch $1/PAR_hg38.bed \
+    [ ! -s $1/af/$CHOICE/gnomad_PASS_SNV_chrXPAR_high_missingness.starch ] &&
+        bedops --intersect $1/af/$CHOICE/gnomad_PASS_SNV_chrX_high_missingness.starch $1/PAR_hg38.bed \
             | starch - \
-            > $1/af/gnomad_PASS_SNV_chrXPAR_high_missingness.starch
+            > $1/af/$CHOICE/gnomad_PASS_SNV_chrXPAR_high_missingness.starch
     
-    [ ! -s $1/af/gnomad_PASS_SNV_chrXnotPAR_high_missingness.starch ] &&
-        bedops --intersect $1/af/gnomad_PASS_SNV_chrX_high_missingness.starch $1/chrXnotPAR_hg38.bed \
+    [ ! -s $1/af/$CHOICE/gnomad_PASS_SNV_chrXnotPAR_high_missingness.starch ] &&
+        bedops --intersect $1/af/$CHOICE/gnomad_PASS_SNV_chrX_high_missingness.starch $1/chrXnotPAR_hg38.bed \
             | starch - \
-            > $1/af/gnomad_PASS_SNV_chrXnotPAR_high_missingness.starch
+            > $1/af/$CHOICE/gnomad_PASS_SNV_chrXnotPAR_high_missingness.starch
 
-    [ ! -s $1/af/gnomad_PASS_SNV_autosomesAndPAR_high_missingness.starch ] &&
-        starchcat $1/af/gnomad_PASS_SNV_chr[1-9]*_high_missingness.starch $1/af/gnomad_PASS_SNV_chrXPAR_high_missingness.starch \
-            > $1/af/gnomad_PASS_SNV_autosomesAndPAR_high_missingness.starch 
+    [ ! -s $1/af/$CHOICE/gnomad_PASS_SNV_autosomesAndPAR_high_missingness.starch ] &&
+        starchcat $1/af/$CHOICE/gnomad_PASS_SNV_chr[1-9]*_high_missingness.starch $1/af/$CHOICE/gnomad_PASS_SNV_chrXPAR_high_missingness.starch \
+            > $1/af/$CHOICE/gnomad_PASS_SNV_autosomesAndPAR_high_missingness.starch 
 
     log "Removing positions with high missingness"
-    [ ! -s $1/qc/confidentRegions_nolowcov_nohighmissingness_hg38_autosomesAndPAR.starch ] &&
-        bedops --difference $1/qc/confidentRegions_nolowcov_hg38_autosomesAndPAR.starch $1/af/gnomad_PASS_SNV_autosomesAndPAR_high_missingness.starch \
+    mkdir -p $1/qc/$CHOICE
+    [ ! -s $1/qc/$CHOICE/confidentRegions_nolowcov_nohighmissingness_hg38_autosomesAndPAR.starch ] &&
+        bedops --difference $1/qc/confidentRegions_nolowcov_hg38_autosomesAndPAR.starch $1/af/$CHOICE/gnomad_PASS_SNV_autosomesAndPAR_high_missingness.starch \
         | starch - \
-        > $1/qc/confidentRegions_nolowcov_nohighmissingness_hg38_autosomesAndPAR.starch 
+        > $1/qc/$CHOICE/confidentRegions_nolowcov_nohighmissingness_hg38_autosomesAndPAR.starch 
     
-    [ ! -s $1/qc/confidentRegions_nolowcov_nohighmissingness_hg38_chrXnotPAR.starch ] &&
-        bedops --difference $1/qc/confidentRegions_nolowcov_hg38_chrXnotPAR.starch $1/af/gnomad_PASS_SNV_chrXnotPAR_high_missingness.starch \
+    [ ! -s $1/qc/$CHOICE/confidentRegions_nolowcov_nohighmissingness_hg38_chrXnotPAR.starch ] &&
+        bedops --difference $1/qc/confidentRegions_nolowcov_hg38_chrXnotPAR.starch $1/af/$CHOICE/gnomad_PASS_SNV_chrXnotPAR_high_missingness.starch \
         | starch - \
-        > $1/qc/confidentRegions_nolowcov_nohighmissingness_hg38_chrXnotPAR.starch
+        > $1/qc/$CHOICE/confidentRegions_nolowcov_nohighmissingness_hg38_chrXnotPAR.starch
     
     end=$(date +%s)
     runtime=$(((end-start)/60))
@@ -178,13 +213,45 @@ extract_snvs() {
     log "Time Taken" "$runtime minutes"
 }
 
-update_allele() {
+extract_snvs_specific() {
     start=$(date +%s)
+    CHOICE=$2
+    while read -r chroms; do
+        log "Extracting chrom $chroms"
+        if [ ! -s $1/af/$CHOICE/gnomad_PASS_SNV_chr${chroms}_af_highconf.starch ]; then
+            bedmap --echo --skip-unmapped $1/af/$CHOICE/gnomad_PASS_SNV_chr${chroms}_af.starch $1/qc/$CHOICE/confidentRegions_nolowcov_nohighmissingness_hg38_autosomesAndPAR.starch \
+            | starch - \
+            > $1/af/$CHOICE/gnomad_PASS_SNV_chr${chroms}_af_highconf.starch &
+        else
+            log "  Already downloaded... skipping."
+        fi
+    done < $1/chromList.txt
+    wait
+   
+    log "Recomputing for autosomal regions and non-PAR regions"
+    [ ! -s $1/af/$CHOICE/gnomad_PASS_SNV_chrXPAR_af_highconf.starch ] &&
+        bedmap --echo --skip-unmapped $1/af/$CHOICE/gnomad_PASS_SNV_chrX_af.starch $1/qc/$CHOICE/confidentRegions_nolowcov_nohighmissingness_hg38_autosomesAndPAR.starch \
+        | starch - \
+        > $1/af/$CHOICE/gnomad_PASS_SNV_chrXPAR_af_highconf.starch 
+    
+    [ ! -s $1/af/$CHOICE/gnomad_PASS_SNV_chrXnotPAR_af_highconf.starch ] &&
+        bedmap --echo --skip-unmapped $1/af/$CHOICE/gnomad_PASS_SNV_chrX_af.starch $1/qc/$CHOICE/confidentRegions_nolowcov_nohighmissingness_hg38_chrXnotPAR.starch \
+        | starch - \
+        > $1/af/$CHOICE/gnomad_PASS_SNV_chrXnotPAR_af_highconf.starch 
+    
+    end=$(date +%s)
+    runtime=$(((end-start)/60))
+    log "Time Taken" "$runtime minutes"
+}
+
+update_allele_specific() {
+    start=$(date +%s)
+    CHOICE=$2
     seq 1 22 | cat - <(echo -e "XPAR\nXnotPAR") > $1/chromList_PARsplit.txt
     while read -r chroms; do
         log "Extracting chrom $chroms"
-        if [ ! -s $1/af/gnomad_PASS_SNV_chr${chroms}_af_highconf_wrongref_idx_newref.starch ]; then
-            unstarch $1/af/gnomad_PASS_SNV_chr${chroms}_af_highconf.starch \
+        if [ ! -s $1/af/$CHOICE/gnomad_PASS_SNV_chr${chroms}_af_highconf_wrongref_idx_newref.starch ]; then
+            unstarch $1/af/$CHOICE/gnomad_PASS_SNV_chr${chroms}_af_highconf.starch \
                 | awk -v OFS='\t' -F'\t' '{if($4 != $10){ \
                 printf "%s\t%s\t%s\t%s\t%s\n", $1, $2-3, $2-2, $10, 1; \
                 printf "%s\t%s\t%s\t%s\t%s\n", $1, $2-2, $2-1, $10, 2; \
@@ -195,7 +262,7 @@ update_allele() {
                 printf "%s\t%s\t%s\t%s\t%s\n", $1, $3+2, $3+3, $10, 7;}}' \
                 | sort-bed - \
                 | starch - \
-                > $1/af/gnomad_PASS_SNV_chr${chroms}_af_highconf_wrongref_idx_newref.starch &
+                > $1/af/$CHOICE/gnomad_PASS_SNV_chr${chroms}_af_highconf_wrongref_idx_newref.starch &
         else
             log "  Already extracted... skipping."
         fi
@@ -221,6 +288,7 @@ main() {
     OUTDIR=""
     COVERAGE=0.033
     WD="."
+    OPTIONS="male female"
     for i in "$@"; do
     case $i in
         -o|--outdir)
@@ -243,6 +311,11 @@ main() {
         shift
         shift
         ;;
+        -ch|--choice)
+        OPTIONS="$2"
+        shift
+        shift
+        ;;
         -h|--help)
         usage
         exit
@@ -256,18 +329,26 @@ main() {
     
     log "Computing high-confidence, low coverage regions." "..." "STEP 2A"
     extract_highconf_lowcov_regions $OUTDIR $GNOMADDIR $COVERAGE && log "SUCCESSFUL" "High Confident, Low Coverage Starch files generated" "STEP 2A" || die "Step 2A failed"
-   
-    log "Computing SNVs that pass filters" "..." "STEP 2B"
-    find_passing_snvs $OUTDIR $GNOMADDIR $WD && log "SUCCESSFUL" "SNVs filtered" "STEP 2B" || die "Step 2B failed"
+  
+    for CHOICE in $OPTIONS; do
+        log "Computing SNVs that pass filters for $CHOICE" "..." "STEP 2B"
+        find_passing_snvs_specific $OUTDIR $GNOMADDIR $WD $CHOICE && log "SUCCESSFUL" "SNVs filtered" "STEP 2B" || die "Step 2B failed"
+    done
 
     log "Computing SNVs that are present in more than 1000 alleles" "..." "STEP 2C"
-    find_high_missingness $OUTDIR && log "SUCCESSFUL" "SNVs filtered" "STEP 2C" || die "Step 2C failed"
+    for CHOICE in $OPTIONS; do 
+        find_high_missingness_specific $OUTDIR $CHOICE && log "SUCCESSFUL" "SNVs filtered" "STEP 2C" || die "Step 2C failed"
+    done
 
     log "Extract SNVs in high confidence, high coverage regions" "..." "STEP 2D"
-    extract_snvs $OUTDIR && log "SUCCESSFUL" "SNVs filtered" "STEP 2D" || die "Step 2D failed"
+    for CHOICE in $OPTIONS; do 
+        extract_snvs_specific $OUTDIR $CHOICE && log "SUCCESSFUL" "SNVs filtered" "STEP 2D" || die "Step 2D failed"
+    done
     
     log "Updating hg38 reference allele" "..." "STEP 2E"
-    update_allele $OUTDIR && log "SUCCESSFUL" "Reference updated." "STEP 2E" || die "Step 2E failed"
+    for CHOICE in $OPTIONS; do 
+        update_allele_specific $OUTDIR $CHOICE && log "SUCCESSFUL" "Reference updated." "STEP 2E" || die "Step 2E failed"
+    done
     
     log "QC Complete" "..." "STEP 2"
     
